# Generated by Emerald single-run Qupacabrathon precomputation.
# Emerald single-run v0.8: policy=robust, SHOTS=340, cost=$11.8160, DELTA~0.043565, family=fourier1
def build_circuits(n: int, theta: float) -> list[Callable[[], None]]:
    if n != 7:
        raise ValueError(f"precomputed strategy is for C_7, got C_{n}")

    alice_angles = (
        0.0017794413724914193,
        2.6943042278289795,
        5.3870196342468262,
        8.0794820785522461,
        10.771439552307129,
        13.463019371032715,
        16.154630661010742,
    )
    bob_angles = (
        0.22409924864768982,
        2.9165549278259277,
        5.6103458404541016,
        8.3041315078735352,
        10.996576309204102,
        13.687353134155273,
        16.377391815185547,
    )

    def gates_for(x: int, y: int) -> Callable[[], None]:
        angle_a = alice_angles[x]
        angle_b = bob_angles[y]

        def circuit() -> None:
            qml.Hadamard(wires=0)
            qml.CNOT(wires=[0, 1])
            qml.RY(angle_a, wires=0)
            qml.RY(angle_b, wires=1)

        return circuit

    return [gates_for(x, y) for x, y in question_order(n)]
