# Generated by aggressive_precompute.py.
# Paste this function (and only this function) into a copy of
# challenge/submission-template.py. The template already imports qml and Callable.
# family=affine; N=13; shots=293

def build_circuits(n: int, theta: float) -> list[Callable[[], None]]:
    if n != 13:
        raise ValueError(f"precomputed strategy is for C_13, got C_{n}")
    # theta is intentionally unused: all requested angles were compiled offline.
    alice_angles = (
        +0,
        +2.8999316802367323,
        +5.7998633604734646,
        +8.699795040710196,
        +11.599726720946929,
        +14.499658401183662,
        +17.399590081420392,
        +20.299521761657125,
        +23.199453441893858,
        +26.099385122130592,
        +28.999316802367325,
        +31.899248482604055,
        +34.799180162840784,
    )
    bob_angles = (
        +0.1208304866765305,
        +3.0207621669132627,
        +5.9206938471499955,
        +8.820625527386726,
        +11.720557207623459,
        +14.620488887860192,
        +17.520420568096924,
        +20.420352248333657,
        +23.32028392857039,
        +26.220215608807123,
        +29.120147289043857,
        +32.020078969280583,
        +34.920010649517316,
    )

    def gates_for(x: int, y: int) -> Callable[[], None]:
        angle_a = alice_angles[x]
        angle_b = bob_angles[y]

        def circuit() -> None:
            qml.Hadamard(wires=0)
            qml.CNOT(wires=[0, 1])
            qml.RY(angle_a, wires=0)
            qml.RY(angle_b, wires=1)

        return circuit

    return [gates_for(x, y) for x, y in question_order(n)]
