# Generated by aggressive_precompute.py.
# Paste this function (and only this function) into a copy of
# challenge/submission-template.py. The template already imports qml and Callable.
# family=affine; N=3; shots=181

def build_circuits(n: int, theta: float) -> list[Callable[[], None]]:
    if n != 3:
        raise ValueError(f"precomputed strategy is for C_3, got C_{n}")
    # theta is intentionally unused: all requested angles were compiled offline.
    alice_angles = (
        +0,
        +2.0943951023931957,
        +4.1887902047863914,
    )
    bob_angles = (
        +0.52359877559829882,
        +2.6179938779914944,
        +4.7123889803846906,
    )

    def gates_for(x: int, y: int) -> Callable[[], None]:
        angle_a = alice_angles[x]
        angle_b = bob_angles[y]

        def circuit() -> None:
            qml.Hadamard(wires=0)
            qml.CNOT(wires=[0, 1])
            qml.RY(angle_a, wires=0)
            qml.RY(angle_b, wires=1)

        return circuit

    return [gates_for(x, y) for x, y in question_order(n)]
